title: "State of Monroe Legal System"
description: "Official legal documents and resources for the State of Monroe."

# Use theme gem
theme: minimal-mistakes-jekyll

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# URL settings
url: "https://absoro.github.io"
baseurl: ""

# Author settings
author:
  name: "State of Monroe"

# Navigation settings
collections:
  pages:
    output: true

# Include the custom stylesheet
sass:
  load_paths:
    - _sass

# Enable sidebar
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      sidebar:
        nav: "main"
