# Site settings
title: "State of Monroe Legal System"
description: "Official legal documents and resources for the State of Monroe."
theme: just-the-docs

# URL of your site (replace 'yourusername' with your GitHub username)
url: "https://absoro.github.io"
baseurl: "" # Leave this empty unless your site is in a subdirectory

# Enable search functionality
search_enabled: true

# Navigation links in the top right corner
aux_links:
  Home:
    url: "/"
    external: false
