remote_theme: mmistakes/minimal-mistakes@latest

plugins:
  - jekyll-include-cache

title: "State of Monroe Legal System"
description: "Official legal documents and resources for the State of Monroe."

# URL settings
url: "https://absoro.github.io"
baseurl: ""

# Author settings
author:
  name: "State of Monroe"

# Theme settings
theme: minimal-mistakes-jekyll

# Navigation settings
collections:
  pages:
    output: true

# Include the custom stylesheet
sass:
  load_paths:
    - _sass
