remote_theme: just-the-docs/just-the-docs@v0.3.3

title: "Ranch Legal"
description: "Legal resources for Ranch Roleplay"

markdown: kramdown
kramdown:
  parse_block_html: true

sass:
  sass_dir: _sass
  style: compressed

# Remove any color_scheme specification if present
